# Generated by Django 3.2.16 on 2023-09-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0002_booking_feedback_landarea_landowner_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
